<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_detail_absen_model extends CI_Model
{

    public $table = 'tbl_detail_absen';
    public $id = 'id_kyn';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    //join tabel karyawan dan tabel detail absensi
    function duatabel($jenis_absen='', $fromdate='', $todate=''){
        $this->db->select('*');
        $this->db->from('tbl_karyawan');
        $this->db->join('tbl_detail_absen','tbl_detail_absen.nik = tbl_karyawan.nik');
        if($jenis_absen!=''){
              $this->db->like('j_absen',$jenis_absen);
        }
        if($fromdate!=''){
            $this->db->where('tgl >=', $fromdate);
        }
        if($todate!=''){
            $this->db->where('tgl <=', $todate);
        }
        $query = $this->db->get();
        if($query->num_rows() != 0){
            return $query->result();
        } else {
        return false;
        }
    }    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_kyn', $q);
        // $this->db->or_like('nama_kyn', $q);
        $this->db->or_like('j_absen', $q);
        $this->db->or_like('tgl', $q);
        $this->db->or_like('jam', $q);
        $this->db->or_like('keterangan', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_kyn', $q);
        // $this->db->or_like('nama_kyn', $q);
        $this->db->or_like('j_absen', $q);
        $this->db->or_like('tgl', $q);
        $this->db->or_like('jam', $q);
        $this->db->or_like('keterangan', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function GetAbs($where= "")
    {
      $data = $this->db->query('select * from abs '.$where);
      return $data;
    }
    function GetKary($where= "")
    {
        $data = $this->db->query('select * from tbl_karyawan '.$where);
        return $data;
    }

    function GetBulan($where= "")
    {
        $data = $this->db->query('select * from month '.$where);
        return $data;
    }

    function GetTahun($where= "")
    {
        $data = $this->db->query('select * from year '.$where);
        return $data;
    }

    function karyawan($nik){
        return $this->db->query("select * from tbl_karyawan where nik = '$nik'");
    }
}

/* End of file Tbl_detail_absen_model.php */
/* Location: ./application/models/Tbl_detail_absen_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-30 08:17:10 */
/* http://harviacode.com */