<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_karyawan_model extends CI_Model
{

    public $table = 'tbl_karyawan';
    public $id = 'nik';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function filter($jenis_kelamin='', $fromdate='', $todate=''){
        $this->db->select('*');
        $this->db->from('tbl_karyawan');
        if($jenis_kelamin!=''){
            $this->db->like('j_kel',$jenis_kelamin);
        }
        if($fromdate!=''){
            $this->db->where('tgl_lahir >=', $fromdate);
        }
        if($todate!=''){
            $this->db->where('tgl_lahir <=', $todate);
        }
        $query = $this->db->get();
        if($query->num_rows() != 0){
            return $query->result();
        } else {
        return false;
        }
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('nik', $q);
        $this->db->or_like('nama_kyn', $q);
        $this->db->or_like('tgl_lahir', $q);
        $this->db->or_like('j_kel', $q);
        $this->db->or_like('alamat', $q);
        $this->db->or_like('no_tlp', $q);
        $this->db->or_like('jabatan', $q);
        $this->db->or_like('join_date', $q);
        $this->db->or_like('end_date', $q);
        $this->db->or_like('status', $q);
        $this->db->or_like('foto', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('nik', $q);
        $this->db->or_like('nama_kyn', $q);
        $this->db->or_like('tgl_lahir', $q);
        $this->db->or_like('j_kel', $q);
        $this->db->or_like('alamat', $q);
        $this->db->or_like('no_tlp', $q);
        $this->db->or_like('jabatan', $q);
        $this->db->or_like('join_date', $q);
        $this->db->or_like('end_date', $q);
        $this->db->or_like('status', $q);
        $this->db->or_like('foto', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($nik)
    {
        $this->db->where('nik', $nik);
        $this->db->delete('tbl_karyawan');
    }

    function pendidikan($nik){
        return $this->db->query("select * from tbl_pendidikan where nik = '$nik'");
    }
    function keluarga($nik){
        return $this->db->query("select * from tbl_keluarga where nik = '$nik'");
    }
    function GetJab($where= "")
    {
      $data = $this->db->query('select * from tbl_jabatan '.$where);
      return $data;
    }
    function GetKel($where= "")
    {
        $data = $this->db->query('select * from j_kelamin '.$where);
        return $data;
    }
    function GetStat($where= "")
    {
        $data = $this->db->query('select * from s_pegawai '.$where);
        return $data;
    }
    function GetKwn($where= "")
    {
        $data = $this->db->query('select * from s_kawin '.$where);
        return $data;
    }

}

/* End of file Tbl_karyawan_model.php */
/* Location: ./application/models/Tbl_karyawan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-23 04:25:29 */
/* http://harviacode.com */